Parsers are Spring Beans now
Leoltron/liquid-log pull request #13
Opened 2018-11-13 20:47 UTC by Leoltron

https://github.com/Leoltron/liquid-log/issues/12 @ykalemi

2018-11-14 06:54 UTC, ykalemi requested changes

2018-11-14 06:54 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/UniversalLogParser.java
> +        Object[] additionalData = new Object[0];
Не ООП-подход передавать в качестве аргументов нетипизированный массив. Это не безопасно для будущих рефакторингов.

2018-11-14 06:54 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        ITimeParser timeParser = getTimeParser((String) additionalData[0]);
Теперь на каждую строку вы создаёте новый объект - TimeParser. Если строк будут десятки миллионов, то парсинг будет генерировать огромное количество мусора.
И это всё при том, что часовой пояс постоянен для всего файла, и не меняется от строчки к строчке.

2018-11-14 06:54 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
>      private Pair<Long, DataSet> currentPair;
Вы сделали TopParser spring-бином, но он:
 - хранит состояние (текущий dataset
 - хранит часовой пояс, который постоянно пересчитывается

При этом аннотация `@Component` указывает, что данный бин является синглтоном. Из этого следует, что ваш код не является безопасным при многопользовательской работе.

Это было прямо в задании указано:
>  который не должен хранить никакого состояния (текущий DataSet, например)

2018-11-14 06:54 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/UniversalLogParser.java
> +
Предлагаю TimeParser создавать где-то на данном этапе, так как он один на весь файл. Тогда уйдёт много сопутствующих проблем.

2018-11-14 06:54 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +    public LogParseModes(GCParser gcParser, SdngParser sdngParser, TopParser topParser)
На данный момент этот код можно оставить. Но хочу, чтобы вы поняли - этот код не очень хорош для будущего расширения. Например, когда нужно будет добавить новый парсер - придётся его добавлять в этот конструктор, и далее по всему классу.

2018-11-14 09:02 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/UniversalLogParser.java
> +
Типа отдавать парсеру вместо часового пояса и всего прочего ITimeParser?

2018-11-14 09:08 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +    public LogParseModes(GCParser gcParser, SdngParser sdngParser, TopParser topParser)
Я правильно понял, это можно сделать через бины?

2018-11-14 11:02 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +    public LogParseModes(GCParser gcParser, SdngParser sdngParser, TopParser topParser)
Да. Есть несколько вариантов, они все были в лекции так или иначе рассмотрены. Это можно отложить до одной из будущих задач.

2018-11-14 11:03 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/UniversalLogParser.java
> +
Да, именно. Вам его нужно создать всего один раз (а не как сейчас - на каждую строку). Ну и не нужно передавать эти additionalData.

2018-11-15 08:12 UTC, ykalemi requested changes

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogDataWriter.java
> +    public synchronized void onDataChunkFinished(Long time)
почему понадобился synchronized?

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +    public LogParseModes(List<ILogParser<Long, DataSet>> logParsers, List<AbstractTimeParserBuilder> timeParserBuilders)
:+1:

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/AbstractTimeParserBuilder.java
> +public abstract class AbstractTimeParserBuilder implements IModeCompatible
Мне кажется, для Builder-а не хватает интерфейса

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/UniversalLogParser.java
> +            writer.onDataChunkFinished(timeParser.getLastParsedTime());
у writer-а есть метод close. Этот вызов точно не стоит туда поместить?

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +        String[] compatibleModesCopy = new String[compatibleModes.length];
зачем каждый раз создаётся копия?

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/sdng/SdngTimeParserBuilder.java
> +        return new String[]{"cdng"};
cd? Эта опечатка, кстати, отличный пример того, почему нужно использовать константы

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
TopParser - синглтон. Но для каждого нового файла у него назначается новый dataStorage. Что будет, если два файла будут парситься параллельно?

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +    public TopParser(IDataParser<TopData> dataParser)
Spring тут помогает, тем что сам догадался сделать `@Autowired`. Но всё же хорошим стилем является писать это явно. Для улучшения читаемости

2018-11-15 08:12 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/gc/GCTimeParserBuilder.java
> +@Scope("prototype")
Какого эффекта вы хотите добиться, добавляя prototype? Проверяли ли вы это?

2018-11-15 08:15 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +        String[] compatibleModesCopy = new String[compatibleModes.length];
А как еще безопасно передать массив? Т.е., так, чтобы его было нельзя изменить снаружи.

2018-11-15 08:17 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
Я планировал, что DataStorage тоже будет синглтоном. Поэтому и сделал его метод synchronized. Но сейчас я не уверен, что это хорошая идея.

2018-11-15 08:17 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +    public TopParser(IDataParser<TopData> dataParser)
Понятно, буду знать

2018-11-15 08:22 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
На данный момент этот код вызывается в одном потоке. Synchronized просто лишний

2018-11-15 08:22 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +        String[] compatibleModesCopy = new String[compatibleModes.length];
Например, сразу использовать unmodifiableList

2018-11-15 08:24 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
Упс, промахнулся. Этот метод - я имел в виду, который synchronized.

Здесь-то как раз проблема, что параллельный вызов будет перетирать значение

2018-11-15 08:48 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/sdng/SdngTimeParserBuilder.java
> +        return new String[]{"cdng"};
Мда, действительно. Выделю все названия режимов куда-нибудь

2018-11-15 08:51 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
Я почему- то забыл реализовать желание сделать DataStorage синглтоном => бином. Сейчас сделаю это и в этом методе просто не будет необходимости.

2018-11-15 08:52 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/gc/GCTimeParserBuilder.java
> +@Scope("prototype")
Еще нет, систему пришлось переустановить, делал пока вслепую. Меня вообще почему-то удивляет, что аргумент Scope - не Enum. Видимо, я что-то упускаю в лекциях.

2018-11-15 16:57 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/top/TopParser.java
> +        this.dataStorage = dataStorage;
А, понятно, я перепутал логику работы этого класса -_- придется передавать dataStorage вместе с timeParser-ом, но это уже напрашивается на композицию

2018-11-16 09:24 UTC, ykalemi approved these changes

2018-11-16 09:24 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +        return ctx.getBean(timeParser.getClass());
Мне всё равно это не очень нравится, потому что мы храним бин только для того, чтобы узнать его класс. Вообще, с моей точки зрения, builder должен быть снинглтоном. И это должен быть, скорее, не builder, а просто фабрика, которая будет возвращать нужный TimeParser (все нужные аргументы передаём в метод, а не храним в билдере). Тогда всё будет намного чище.

Можно отложить, ещё будет такая задача.

2018-11-16 10:54 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/LogParseModes.java
> +        return ctx.getBean(timeParser.getClass());
Хорошо, тогда я просто продолжу это в ветке Task9, кажись, 8 и 9 задания независимы.

2018-11-16 10:55 UTC, merged