Added GetCatalogsAction to counted actions
Leoltron/liquid-log pull request #4
Opened 2018-10-06 10:12 UTC by Leoltron

@d0k1 https://github.com/Leoltron/liquid-log/issues/2

2018-10-07 15:55 UTC, Leoltron commented
@ykalemi  @etitov

2018-10-08 07:20 UTC, ykalemi requested changes
А вы проверяли написанный код, запускали приложение?

У вас нет изменений клиентской части, поэтому сделанные изменения нигде не отображаются

2018-10-08 19:38 UTC, Leoltron commented
Действительно, проглядел, исправлено.

2018-10-09 07:16 UTC, ykalemi approved these changes

2018-10-09 09:08 UTC, merged