Extracted database interaction to a separate class, refactoring
Leoltron/liquid-log pull request #9
Opened 2018-10-23 18:17 UTC by Leoltron

https://github.com/Leoltron/liquid-log/issues/7 @d0k1 @ykalemi @etitov

2018-10-24 14:34 UTC, ykalemi requested changes
- Не написаны тесты
- Не выполнена часть про минимально доступный интерфейс - нет метода `DataSet get(long key);` Я могу это принять, если вы это хоть как-то обоснуете. Но на данный момент это выглядит как пропуск части задания

2018-10-24 14:34 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +                dataConsumer.consume(currentPair);
Я хочу, чтобы вы написали тест на LogParser.parseLine:
- передать ему две строки, у которых в результате будут разные roundedTime (это можно через Mock-и сделать)
- и проверить сколько раз вызывается dataConsumer.consume

2018-10-24 14:34 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +            currentPair = new Pair<>(roundedTime, new DataSet());
а нужна эта абстракция Pair? Если время становится частью DataSet - то, может, пусть оно прямо в DataSet и переедет? Ну или давайте просто передавать два аргумента, зачем их делать неявными?

2018-10-24 14:34 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/PerfhouseApplication.java
> +            Main.main(args);
Я ожидал, конечно, немного другое название :)

2018-10-24 15:03 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +            currentPair = new Pair<>(roundedTime, new DataSet());
Я держу данные разрозненными, чтобы позже было легче разбить DataSet на отдельные наборы данных. И в их общего предка я уже и запихну поле со временем.

2018-10-24 15:06 UTC, Leoltron commented
Возможно, я неправильно понял суть задания. Я не понимаю, зачем классу для **выгрузки** данных в БД метод для получения данных по ключу?

2018-10-24 16:34 UTC, ykalemi commented
> Возможно, я неправильно понял суть задания. Я не понимаю, зачем классу для **выгрузки** данных в БД метод для получения данных по ключу?

С этого тогда стоило начать, или по крайней мере прокомментировать код - почему вы решили не делать такой интерфейс. Потому что это все-таки отступление от условий.
В постановке предполагалось, что появится класс с условным названием "Хранилище". У хранилища вполне допустим метод get, который вернет текущий на данный момент набор данных.
Можно оставить как есть, но на будущее - давайте сначала обсуждать.

Про тесты вопрос в силе. Потому что у вас в коде есть ошибка, которая бы обнаружилась при написании теста.

2018-10-24 16:41 UTC, Leoltron commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +                dataConsumer.consume(currentPair);
Я понял, о каком баге идет речь, сейчас заодно и исправлю.

2018-10-24 16:42 UTC, Leoltron commented
Если речь о том тесте, что был предложен ранее, то я не стал его делать, чтобы не отклоняться от первоначальной задачи еще сильнее, как это было в прошлом PR. Ибо тест не для `LogDataWriter`, а для `LogParser`.

2018-10-24 16:46 UTC, ykalemi commented
Ну, дело в том, что вы не стали реализовывать предложенный интерфейс, а следовательно у вас изменились итоговые классы и требования в тестам тоже приходится менять. У вас ошибка в коде, напишите тест

2018-10-24 19:33 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/LogParser.java
> +            dataConsumer.consume(currentPair);
currentPair может быть null? Например, если файл оказался пустой

2018-10-25 07:55 UTC, ykalemi approved these changes

2018-10-25 07:56 UTC, merged